# Generated by Django 6.0.6 on 2026-06-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.IntegerField(db_column='ProductID', primary_key=True, serialize=False)),
                ('productname', models.CharField(blank=True, db_column='ProductName', max_length=200, null=True)),
                ('is_active', models.SmallIntegerField(blank=True, db_column='Is_Active', null=True)),
            ],
            options={
                'db_table': 'PRODUCT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('categoryid', models.IntegerField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(blank=True, db_column='CategoryName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'PRODUCT_CATEGORY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.IntegerField(db_column='RegionID', primary_key=True, serialize=False)),
                ('regionname', models.CharField(blank=True, db_column='RegionName', max_length=100, null=True)),
            ],
            options={
                'db_table': 'REGION',
                'managed': False,
            },
        ),
    ]
